name: three_dgs_real
description: Cross-platform Flutter client for guided photo capture and 3D Gaussian Splatting reconstruction.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.7
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  dio: ^5.7.0
  path_provider: ^2.1.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
